  # Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  MSBUILD: '"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Msbuild\\Current\\Bin\\MSBuild.exe"'
  BL_PATH: '"C:\\Program Files (x86)\\GeneXus\\GeneXus17\\TeamDev.msbuild"'
  WORKING_DIR: '"C:\AzureCheckouts"'
  KB_ALIAS: '"JenkinsClient"'
  SERVER_URL: '"https://sandform.genexusserver.com/kbs"'
  USER: '"gxtechnical\nachob97"'
  PASS: $(password)

trigger:
- main

pool:
  name: CustomBuild

steps:
- script: $(MSBUILD) $(BL_PATH) -target:CreateKB /p:WorkingDirectory=$(WORKING_DIR);CreateDbInKbFolder=True;DbaseName=$(KB_ALIAS);DbaseUseIntegratedSecurity=True;ServerUrl=$(SERVER_URL);ServerKbAlias=$(KB_ALIAS);ServerUsername=$(USER);ServerPassword=$(PASS) > executed.txt
  displayName: 'Create KB'
