  # Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  MSBUILD: '"$(msbuid)"'
  BL_PATH: '"$(genexus)"'
  WORKING_DIR: '"$(kbpath)\\$(KB_ALIAS)"'
  KB_ALIAS: '"ActualizacionAmbiente2"'
  GXSERVER_URL: '"$(serverurl)"'
  GXSERVER_USER: '"$(serveruser)"'
  GXSERVER_PASS: $(password)

trigger:
- main

pool:
  name: $(agent)

steps:
- script: $(MSBUILD) $(BL_PATH)\AzureCICD.msbuild -target:CreateOrUpdateKB /p:WorkingDirectory=$(WORKING_DIR);CreateDbInKbFolder=True;DbaseName=$(KB_ALIAS);DbaseUseIntegratedSecurity=True;ServerUrl=$(GXSERVER_URL);ServerKbAlias=$(KB_ALIAS);ServerUsername=$(GXSERVER_USER);ServerPassword=$(GXSERVER_PASS)
  displayName: 'Create or Update KB'

- script: $(MSBUILD) $(BL_PATH)\teamdev.Msbuild -target:Build /p:WorkingDirectory=$(WORKING_DIR)
  displayName: 'Build KB'
