  # Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  MSBUILD: '"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Msbuild\\Current\\Bin\\MSBuild.exe"'
  BL_PATH: '"C:\Program Files (x86)\GeneXus\GeneXus17"'
  WORKING_DIR: '"C:\\AzureCheckouts"'
  KB_ALIAS: '"JenkinsClient"'
  SERVER_URL: '"https://sandform.genexusserver.com/kbs"'
  USER: '"gxtechnical\nachob97"'
  PASS: $(password)
  RUN: $(Build.BuildNumber)

trigger:
- main

pool:
  name: CustomBuild

steps:
- script: | 
    $(MSBUILD) $(BL_PATH)\teamdev.Msbuild -target:CreateKB /p:WorkingDirectory=$(WORKING_DIR)\$(RUN);CreateDbInKbFolder=True;DbaseName=$(RUN)$(KB_ALIAS);DbaseUseIntegratedSecurity=True;ServerUrl=$(SERVER_URL);ServerKbAlias=$(KB_ALIAS);ServerUsername=$(USER);ServerPassword=$(PASS)
    #$(MSBUILD) $(BL_PATH)\teamdev.Msbuild -target:Build
    #$(MSBUILD) $(BL_PATH)\QueryViewerServices.msbuild -target:CreateOrUpdateKB /p:GXInstall=$(BL_PATH);KBDirectory=$(WORKING_DIR);DoUpdate=true;KBServerUri=$(SERVER_URL);KBServerKBAlias=$(KB_ALIAS);GXserverUserName=$(USER);GXserverUserPassword=$(PASS)
  displayName: 'Create or Update KB'
