  # Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  MSBUILD: $(msbuildpath)
  BL_PATH: $(genexus)
  WORKING_DIR: '$(kbpath)\\$(KB_ALIAS)'
  KB_ALIAS: 'ActualizacionAmbiente2'
  GXSERVER_URL: $(serverurl)
  GXSERVER_USER: $(serveruser)
  GXSERVER_PASS: $(password)
  PUBLISH_SETTINGS: $(azurePublish)
  DEPLOYMENT_UNIT: $(deploymentUnit)
  KBENVIRONMENT: $(environment)
  DEPLOY_NAME: $(deploymentUnit)$(Build.BuildNumber)

# Scheduled triggers. Can also be setup through UI, which takes precendence.
schedules:
- cron: "*/10 * * * *"
  displayName: every 10 min trigger
  branches:
   include:
    - main
  always: true

trigger:
- main

pool:
  name: $(agent)

steps:
- script: $(MSBUILD) $(BL_PATH)\AzureCICD.msbuild -target:CreateOrUpdateKB /p:WorkingDirectory=$(WORKING_DIR);CreateDbInKbFolder=True;DbaseName=$(KB_ALIAS);DbaseUseIntegratedSecurity=True;ServerUrl=$(GXSERVER_URL);ServerKbAlias=$(KB_ALIAS);ServerUsername=$(GXSERVER_USER);ServerPassword=$(GXSERVER_PASS)
  displayName: 'Create or Update KB'

- script: $(MSBUILD) $(BL_PATH)\teamdev.Msbuild -target:Build /p:WorkingDirectory=$(WORKING_DIR)
  displayName: 'Build KB'

- script: |
   $(MSBUILD) $(BL_PATH)\deploy.msbuild /t:CreateDeploy /p:KBPath=$(WORKING_DIR);KBEnvironment=$(KBENVIRONMENT);DeploymentUnit=$(DEPLOYMENT_UNIT) /p:ProjectName=$(DEPLOY_NAME) /p:ObjectNames="DeploymentUnitCategory:$(DEPLOYMENT_UNIT)" /p:DEPLOY_TARGETS=" $(BL_PATH)\DeploymentTargets\Azure\azure.targets" /p:DeployFullPath="$(WORKING_DIR)\NetModel\Deploy\AZURE\$(DEPLOYMENT_UNIT)\$(DEPLOY_NAME)" /p:WebSourcePath="$(WORKING_DIR)\NetModel\web" /p:GX_PROGRAM_DIR="$(BL_PATH)" /p:AZURE_PUBLISH_SETTINGS="$(azurePublish)" /p:APPLICATION_KEY="7EE806FE2F1098F88FE35D42546DB8D33B7166F31968A02898ECBDC45D036BA6" /p:INCLUDE_GAM="False" /p:INCLUDE_GXFLOW_BACKOFFICE="True" /p:APP_UPDATE="NONE" /p:ENABLE_KBN="False" /p:PACKAGE_FORMAT="Automatic"

   $(MSBUILD) /ToolsVersion:4.0 "C:\AzureCheckouts\ActualizacionAmbiente2\NetModel\web\$(DEPLOY_NAME).gxdproj" /t:CreatePackage /p:GX_PROGRAM_DIR="C:\Program Files (x86)\GeneXus\GeneXus17" /p:AZURE_PUBLISH_SETTINGS=""C:\Users\ibianchi\Downloads\GeneXusDeploy.PublishSettings"" /p:APPLICATION_KEY="7EE806FE2F1098F88FE35D42546DB8D33B7166F31968A02898ECBDC45D036BA6" /p:INCLUDE_GAM="False" /p:INCLUDE_GXFLOW_BACKOFFICE="True" /p:APP_UPDATE="NONE" /p:ENABLE_KBN="False" /p:PACKAGE_FORMAT="Automatic"
   $(MSBUILD) $(BL_PATH)\DeploymentTargets\Azure\deploy.msbuild /t:Deploy /p:AZURE_PUBLISH_SETTINGS=""C:\Users\ibianchi\Downloads\GeneXusDeploy.PublishSettings"" /p:APPLICATION_KEY="5335ADF697DE7F241142E569A5CDD2D422B42FFC612EF2FBA604A37492313A67" /p:INCLUDE_GAM="False" /p:INCLUDE_GXFLOW_BACKOFFICE="True" /p:APP_UPDATE="NONE" /p:ENABLE_KBN="False" /p:PACKAGE_FORMAT="Automatic" /p:LANGUAGE="41" /p:GENERATOR=".NET" /p:APPLICATION_NAME="$(DEPLOY_NAME)" /p:DEPLOY_PATH="C:\AzureCheckouts\ActualizacionAmbiente2\NetModel\Deploy\AZURE\$(DEPLOYMENT_UNIT)\$(DEPLOY_NAME)" /p:GX_PROGRAM_DIR="C:\Program Files (x86)\GeneXus\GeneXus17" /p:DeploySource="C:\AzureCheckouts\ActualizacionAmbiente2\NetModel\Deploy\AZURE\$(DEPLOY_NAME).zip" /p:CreateCloudPackage="false" /p:KBPath=$(WORKING_DIR) /p:KBEnvironment=".NET" /p:KBVersion="ActualizacionAmbiente2" /p:DeploymentUnit="$(DEPLOYMENT_UNIT)" /p:ProjectName="$(DEPLOY_NAME)" /p:TargetId="AZURE" /p:ObjectNames="DeploymentUnitCategory:$(DEPLOYMENT_UNIT)" /p:ApplicationServer="Kestrel" /p:DEPLOY_TARGETS="C:\Program Files (x86)\GeneXus\GeneXus17\DeploymentTargets\Azure\azure.targets" /p:DeployFullPath="C:\AzureCheckouts\ActualizacionAmbiente2\NetModel\Deploy\AZURE\$(DEPLOYMENT_UNIT)\$(DEPLOY_NAME)" /p:WebSourcePath="C:\AzureCheckouts\ActualizacionAmbiente2\NetModel\web"
   


  displayName: 'Deploy Webapp'