# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  MSBUILD: $(msbuildpath)
  BL_PATH: $(genexus)
  WORKING_DIR: $(workingDir)
  KB_PATH: $(kbpath)
  KB_ALIAS: $(kbalias)
  GXSERVER_URL: $(serverurl)
  GXSERVER_USER: $(serveruser)
  GXSERVER_PASS: $(password)
  PUBLISH_SETTINGS: $(azurePublish)
  DEPLOYMENT_UNIT: $(deploymentUnit)
  KBENVIRONMENT: $(environment)
  KBGENERATOR: $(generator)
  DEPLOY_NAME: $(deploymentUnit)$(Build.BuildNumber)
  APPLICATION_KEY: $(encriptKey)
  FORCE_REBUILD: $(forceRebuild)
  GIT_USER: $(gituser)
  GIT_PASSWORD: $(gitpassword) #This could alternatively be a PAT
  GIT_REPO: $(gitrepo)
  GIT_BRANCH: $(gitbranch) #Branch must exist. Content will be overwritten

# Scheduled triggers. Can also be setup through UI, which takes precendence.
schedules:
  - cron: "*/10 * * * *"
    displayName: every 10 min trigger
    branches:
      include:
        - main
    always: true

trigger:
  - main

pool:
  name: $(agent)

jobs:
  - job: CheckoutOrUpdate
    condition: always()
    steps:
      - script: >
          $(MSBUILD) "$(BL_PATH)\AzureCICD.msbuild" -target:CreateOrUpdateKB /p:WorkingDirectory=$(KB_PATH) /p:CreateDbInKbFolder=True
          /p:DbaseName=$(KB_ALIAS) /p:DbaseUseIntegratedSecurity=True /p:ServerUrl=$(GXSERVER_URL) /p:ServerKbAlias=$(KB_ALIAS) 
          /p:ServerUsername=$(GXSERVER_USER) /p:ServerPassword=$(GXSERVER_PASS)
          
          set /p updateCount=<"$(KB_PATH)\updateCount.txt"

          echo ##vso[task.setvariable variable=updateCount;isOutput=true]%updateCount%
        name: CreateOrUpdateKB



  - job: BuildAndDeploy
    dependsOn: CheckoutOrUpdate
    condition: or(and(succeeded(), gt(dependencies.CheckoutOrUpdate.outputs['CreateOrUpdateKB.updateCount'], '0')),eq(variables['forceRebuild'], 'true'))
    steps:
      - script: rmdir $(KB_PATH)\NetModel /s /q
        condition: eq(variables['forceRebuild'], 'true')
        name: CleanBuildDir

      - script: $(MSBUILD) "$(BL_PATH)\AzureCICD.Msbuild" -target:Build /p:WorkingDirectory=$(KB_PATH) /p:ForceRebuild=$(forceRebuild)
        name: BuildKB

      - script: >
          $(MSBUILD) "$(BL_PATH)\deploy.msbuild" /t:CreateDeploy /p:KBPath=$(KB_PATH);KBEnvironment=$(KBENVIRONMENT);DeploymentUnit=$(DEPLOYMENT_UNIT) 
          /p:ProjectName=$(DEPLOY_NAME) /p:TargetId="AZURE" /p:ObjectNames="DeploymentUnitCategory:$(DEPLOYMENT_UNIT)"
          /p:DEPLOY_TARGETS="$(BL_PATH)\DeploymentTargets\Azure\azure.targets" 
          /p:DeployFullPath="$(KB_PATH)\NetModel\Deploy\AZURE\$(DEPLOYMENT_UNIT)\$(DEPLOY_NAME)" 
          /p:WebSourcePath="$(KB_PATH)\NetModel\web" /p:GX_PROGRAM_DIR="$(BL_PATH)" 
          /p:AZURE_PUBLISH_SETTINGS="$(PUBLISH_SETTINGS)" 
          /p:APPLICATION_KEY="$(APPLICATION_KEY)"
        name: CreateDeploy

      - script: >  
          $(MSBUILD) /ToolsVersion:4.0 "$(KB_PATH)\NetModel\web\$(DEPLOY_NAME).gxdproj" /t:CreatePackage 
          /p:GX_PROGRAM_DIR="$(BL_PATH)" /p:AZURE_PUBLISH_SETTINGS="$(PUBLISH_SETTINGS)" 
          /p:APPLICATION_KEY="$(APPLICATION_KEY)"
        name: CreatePackage

      - script: >
          $(MSBUILD) "$(BL_PATH)\DeploymentTargets\Azure\deploy.msbuild" /t:Deploy 
          /p:AZURE_PUBLISH_SETTINGS="$(PUBLISH_SETTINGS)" 
          /p:APPLICATION_KEY="$(APPLICATION_KEY)" /p:APPLICATION_NAME="$(DEPLOY_NAME)" 
          /p:DEPLOY_PATH="$(KB_PATH)\NetModel\Deploy\AZURE\$(DEPLOYMENT_UNIT)\$(DEPLOY_NAME)" 
          /p:GX_PROGRAM_DIR="$(BL_PATH)" /p:DeploySource="$(KB_PATH)\NetModel\Deploy\AZURE\$(DEPLOY_NAME).zip" 
          /p:CreateCloudPackage="false" /p:KBPath=$(KB_PATH) /p:KBEnvironment="$(KBENVIRONMENT)" /p:KBVersion="ActualizacionAmbiente2" 
          /p:DeploymentUnit="$(DEPLOYMENT_UNIT)" /p:ProjectName="$(DEPLOY_NAME)" /p:TargetId="AZURE" /p:ObjectNames="DeploymentUnitCategory:$(DEPLOYMENT_UNIT)"
          /p:DEPLOY_TARGETS="$(BL_PATH)\DeploymentTargets\Azure\azure.targets" 
          /p:DeployFullPath="$(KB_PATH)\NetModel\Deploy\AZURE\$(DEPLOYMENT_UNIT)\$(DEPLOY_NAME)" 
          /p:WebSourcePath="$(KB_PATH)\NetModel\web" /p:GENERATOR="$(KBGENERATOR)"
        name: DeploytoWebApp
  
  - job: CloneOrPull
    dependsOn: CheckoutOrUpdate
    condition: succeeded()
    steps:
      - script: |
          IF EXIST "GeneXusBuild" (
            cd GeneXusBuild
            git pull
          ) ELSE (
            git clone https://$(GIT_USER):$(GIT_PASSWORD)@$(GIT_REPO)
          )
        workingDirectory: $(WORKING_DIR)
        name: CloneOrPull
      
  - job: PushSourcesToGit
    dependsOn: CloneOrPull
    condition: succeeded()
    steps:
      - script: >
          xcopy /E /I /Y "$(KB_PATH)\NetModel" "$(WORKING_DIR)\GeneXusBuild"

          cd GeneXusBuild

          git add *
        
          git commit -m "Commit build $(Build.BuildNumber)"

          git push -u origin DeploySources
        workingDirectory: $(WORKING_DIR)
        name: CommitPush
